### ISSUE TITLE
[Docs] Generator Async Handling

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/yeoman.github.io#164]
New doc skips any information about `this.async()` and handling asynchronous tasks in generators.

Will need to add!

**Comment by kkemple** [comment]
I experienced some trouble with understanding this, after digging through the source it looks like each method on the base class is using the `run-async` lib which lets you use any of the following:

```javascript
...
writing() {
  return 'do synchronous things...'
}
...
```

```javascript
...
writing() {
  const done = this.async()
  doSomethingAsync((err) => {
    if (err) done(err)
    else done()
  })
}
...
```

```javascript
...
writing() {
  return new Promise((res, rej) => {
    doSomethingAsync((err) => {
      if (err) rej(err)
      else res()
    })
  })
}
...
```

This allows each step of the generator process to run either synchronously or asynchronously

If this is correct and you would like me to add to docs, just point me in the right direction :smile:

**Comment by SBoudrias** [comment]
Yes this is correct. We should add a section on this page http://yeoman.io/authoring/running-context.html
