### ISSUE TITLE
Rename to yeoman.github.io

### ISSUE THREAD

**Issue by silvenon** [yeoman/yeoman.github.io#405]
We talked before about various ways to do this, so that gh-pages branch of other yeoman projects can have a yeoman.io URL, not yeoman.github.io.

Could we assemble a list of suggestions of ways to do this, then vote on it? @arthurvr suggested generators’ URL to be yeoman.io/generator/\<name\>.

Ref. yeoman/generator-gulp-webapp#146.

**Comment by SBoudrias** [comment]
@silvenon Any update on this? Do you want to take care of it?

**Comment by silvenon** [comment]
No, but thanks for pinging, I kinda forgot about this :sweat_smile: Yeah, I will take care of it, I think I have all the necessary info for this to go as smoothly as possible.

**Comment by gaboesquivel** [comment]
consider HTTPS #529

**Comment by silvenon** [comment]
Sorry, I can seem to remember to do this and frankly I'm kinda scared I'll screw it up. Does anybody else want to do this instead?

**Comment by eddiemonge** [comment]
- [ ] Rename repository to yeoman.github.com
- [ ] Rename `master` branch `source`
- [ ] Rename `gh-pages` branch `master`
- [ ] Make `source` branch [the default](https://github.com/yeoman/yeoman.io/settings/branches)
- [ ] Update `build-control` with new branches
- [ ] Update travis config
- [ ] Test updates

**Comment by eddiemonge** [comment]
I miss anything there?

**Comment by silvenon** [comment]
yeoman.github.io*

**Comment by sindresorhus** [comment]
Looks correct to me.

**Comment by eddiemonge** [comment]
Everything is done. However, we have to go through and update links for other things like the generator. http://yeoman.io/generator/

**Comment by eddiemonge** [comment]
nevermind, thats done to in this repo and the yeoman/generator repo

**Comment by silvenon** [comment]
Awesome!

**Comment by SBoudrias** [comment]
We'll need to update contribution information on the README. Now they cd in the wrong repo and there's not note about the branch to use. :heart:
