### ISSUE TITLE
[Doc] Extending yo hooks information in "Creating a generator"/"Managing dependencies"

### ISSUE THREAD

**Issue by ducin** [yeoman/yeoman.github.io#437]
Recently I've been creating custom yo generators and I had to browse the web to find information on how to configure hooks for yeoman (sub)generators. I know this is accessible in the official docs and it is briefly mentioned in the _**Using other tools**_ part of ["_Managing dependencies_"](http://yeoman.io/authoring/dependencies.html) page in the "_Creating a generator_" section, but I think either this page could be extended with more details or a new subpage could be added (such as "_Generator hooks_"). I'm thinking of adding examples that call grunt tasks and listen to events such as `end` or `dependenciesInstalled`.

If you think this makes sense, I'm happy to prepare some markdown pull request.

**Comment by SBoudrias** [comment]
Feel free to send a PR, it is a bit hard to figure what you need exactly.

**Comment by supergray** [comment]
@tkoomzaaskz  waiting for you pr

**Comment by eddiemonge** [comment]
closing in favor of #595
