### ISSUE TITLE
Navbar covers text on FAQ page

### ISSUE THREAD

**Issue by ivywong** [yeoman/yeoman.github.io#492]
When jumping to a question on the FAQ, the navbar covers the question text and part of the answer, which means users have to scroll up. This happens on both Firefox and Chromium.

**Comment by twixie** [comment]
I'm able to confirm this. :+1:

**Comment by piyushdwivedi** [comment]
Is there a reason why the code is structured in the following manner?
`<h3>
   <a> </a>
</h3>
</p>..</p>`
Surely there must be a better structure right? Can someone fill me in on what I'm missing?
