### ISSUE TITLE
Replace lodash with simpler templating tool

### ISSUE THREAD

**Issue by eddiemonge** [yeoman/yeoman.github.io#501]
Lodash is only be used for the generator list to make each item and show the list. Would be nice if it could be replaced with something that is smaller.

**Comment by sindresorhus** [comment]
https://www.npmjs.com/package/lodash.template ? Just need to use `[].forEach()` instead of `_.each()`.

**Comment by arthurvr** [comment]
> https://www.npmjs.com/package/lodash.template

Seems good, though, does lodash have this kind of modularised builds for browsers too? I believe those are on npm (browserify) only.

**Comment by sindresorhus** [comment]
Oh I forgot we don't use browserify here. Maybe we should?

**Comment by eddiemonge** [comment]
seems like that would be overkill for this.

**Comment by arthurvr** [comment]
> Oh I forgot we don't use browserify here. Maybe we should?

:+1: 

> seems like that would be overkill for this.

It wouldn't be especially for this, it just makes things nicer in general. We have some other deps randomly [living](https://github.com/yeoman/yeoman.io/tree/master/app/assets/js/libs) in the repo too.

Generally adding browserify is as easy as 5 lines in a Gruntfile. Not really overhead imho.

**Comment by addyosmani** [comment]
Let's try for browserify. As long as it doesn't overly complicate our tooling (which it shouldn't), I think it's worth experimenting with.
