### ISSUE TITLE
Replace Jekyll with NodeJS compatible

### ISSUE THREAD

**Issue by eddiemonge** [yeoman/yeoman.github.io#512]
It would be nice to get rid of the Ruby dependency. Since we push a static site to the gh-pages branch, we don't actually need jekyll to generate it. Anything like it would work.

**Comment by arthurvr** [comment]
Dunno if we should really spend time on this. We're not running into much concrete issues and Jekyll is really common so everybody knows how to use it.

**Comment by mischah** [comment]
I don't see much of a value in this neither.
