### ISSUE TITLE
Document recommended way of publishing generator forks

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/yeoman.github.io#518]
Regarding https://github.com/yeoman/yeoman/issues/1533#issuecomment-132450964.

Forks meaning generators based on existing ones but with personal tweaks.

[Scoped packages](https://docs.npmjs.com/getting-started/scoped-packages) is the way to go as everyone can have the `generator-angular` name if they want with `@sindresorhus/generator-angular`.

**Comment by arthurvr** [comment]
:+1: 

> Scoped packages is the way to go as everyone can have the generator-angular name if they want with @sindresorhus/generator-angular.

Yeah, I agree.

**Comment by addyosmani** [comment]
I firmly agree with scoped packages being the best way forward here. Perhaps we could start with a tweet from the account that instructs folks to use scoped packages for personal generators and follow up with actual docs?

**Comment by eddiemonge** [comment]
Still needs the package.json updated to be unique. At some point soon, I (or someone can) will remove generators from the list that are forked from a different and don't have a different package.json (not sure what criteria to check, but probably url and author at the least). Ideally the description should state whats different.
