### ISSUE TITLE
Top list `generator: react-fullstack is not a generator

### ISSUE THREAD

**Issue by zckrs** [yeoman/yeoman.github.io#524]
* The master branch is not a Yeoman generator but a boilerplate

* If you check the code source the repository use yeoman only to copy boilerplate (no prompt)

https://github.com/yeoman/yeoman.io/pull/484

If https://github.com/twbs/bootstrap create a branch 'yeoman-generator' who just copy files in new directory and published on NPM.
Should we keep at first position in generator list ???

**Comment by sindresorhus** [comment]
No, that's why we have a blacklist. So many publish junk without even changing the repo URL.

You can add it to: https://github.com/yeoman/yeoman.io/blob/master/app/blacklist.json And anything else you find that shouldn't be in the list.

**Comment by zckrs** [comment]
Already create a PR https://github.com/yeoman/yeoman.io/pull/484  but @SBoudrias closed  :-(

**Comment by sindresorhus** [comment]
Oh, I didn't see that issue. I think it's because we previously just tried to get the URL from the github repo instead of the npm package. This should have been fixed in https://github.com/yeoman/yeoman-generator-list, but I think @SBoudrias reversed the publish of that. Not totally sure though.

**Comment by zckrs** [comment]
Nice :)
But even if the url is recovered from github repo, `generator-react-fullstack` is a con IMO.

![hiha](https://cloud.githubusercontent.com/assets/3020368/9610491/3444c578-50da-11e5-94ff-aa1da1b8df9c.png)

**Comment by sindresorhus** [comment]
@zckrs I don't agree. It might be simple, but it's still better than having to manually get the starter kit.

**Comment by zckrs** [comment]
Ok I understand :-/ sorry.

Sort generator only by github stars is not enough.
Im disappointed when I install this top generator.

https://github.com/yeoman/yeoman.io/issues/459#issuecomment-94584902

**Comment by sindresorhus** [comment]
Keeping open as we're going to somehow fix that generator being at the top.

**Comment by arthurvr** [comment]
Although I wouldn't agree upon blacklisting, it would be cool if it wouldn't be at the top indeed. Maybe just convincing the author to have a separated repo for the generator is enough. I mean, having it in another repo makes the generator more visible for users (and contributors) too.

**Comment by sindresorhus** [comment]
Please read my comment again. https://github.com/yeoman/yeoman.io/issues/524#issuecomment-136784744 This is already fixed, just needs to be correctly deployed.

**Comment by zckrs** [comment]
I do not see a commit that replaced the github link by link npm.

**Comment by eddiemonge** [comment]
closing since its not at the top anymore

**Comment by eddiemonge** [comment]
ugh. just kidding it is still at the top

**Comment by eddiemonge** [comment]
ok closing again as its referenced in the generator page change issue
