### ISSUE TITLE
Generator Blocklist updates

### ISSUE THREAD

**Issue by eddiemonge** [yeoman/yeoman.github.io#527]
We are trying to maintain a clean ecosystem. As part of that, the generator list at yeoman.io/generators polls npm for packages with the `yeoman-generator` keyword. It then makes the list available on the site and in the command line search. There are a few entries that aren't valid (we can't really do much for the duplicates without going through every single one in the registry) and we would like to get these fixed.

If your module is listed below, can you please update the name to be `generator-yourgeneratorname` and publish that version to npm. It'd be nice if you unpublished the incorrect version or added a deprecation notice and removed the `yeoman-generator` keyword so it won't show up in the results.

The following generators don't conform to the naming convention at the minimum. Some may not even be generators. If someone wants to ping the owners, that would be nice. They might also be added to the blacklist.

 - [elm-yeoman-generator](https://github.com/eeue56/elm-yeoman-generator)
    - [x] Contacted to correct problems
    - [x] Added to Blacklist
    - fixed the name and published to npm with new name but left old module still up
    - [ ] remove once old module is unpublished
 - [freshbooks-cli-create-plugin](https://github.com/logankoester/freshbooks-cli-create-plugin)
    - [X] Contacted to correct problems
    - [x] Added to Blacklist
    - [ ] Project fixed the issue
 - [frontendcore-installer](https://github.com/tonipinel/frontendcore)
    - [x] Contacted to correct problems
    - [x] Added to Blacklist
    - [ ] Project fixed the issue
 - [ft-wp](https://github.com/yeoman/generator-webapp)
    - [x] Contacted to correct problems
    - [x] Added to Blacklist
    - [ ] Project fixed the issue
 - [generators-huya](https://github.com/kingback/generators-huya)
    - [x] Contacted to correct problems
    - [x] Added to Blacklist
    - [ ] Project fixed the issue
 - [hajimetest](https://github.com/hajimenagata/generator-gulp-sass-typescript)
    - [x] Contacted to correct problems
    - [x] Added to Blacklist
    - [ ] Project fixed the issue
 - [learning-yeoman-ch6](https://github.com/jonniespratley/learning-yeoman-ch6)
    - [ ] Contacted to correct problems
    - [x] Added to Blacklist
    - [ ] Project fixed the issue
 - [muzzley-generator](https://github.com/assimoes/muzzley-generator)
    - [x] Contacted to correct problems
    - [x] Added to Blacklist
    - [ ] Project fixed the issue
 - [ng-cli](https://github.com/ng-tools/ng-cli)
    - [x] Contacted to correct problems
    - [x] Added to Blacklist
    - [ ] Project fixed the issue
 - [nick-site](https://github.com/xzf158/yeoman-generator-nick-site)
    - [x] Contacted to correct problems
    - [x] Added to Blacklist
    - [ ] Project fixed the issue
 - [yeoman-generator-nick-site](https://github.com/xzf158/yeoman-generator-nick-site)
    - [x] Contacted to correct problems
    - [x] Added to Blacklist
    - [ ] Project fixed the issue
 - [spine-cli](https://github.com/justincosentino/spine)
    - [x] Contacted to correct problems
    - [x] Added to Blacklist
    - [ ] Project fixed the issue
 - [toolbox-utils](https://github.com/frontend/toolbox-utils)
    - [x] Contacted to correct problems
    - [x] Added to Blacklist
    - [ ] Project fixed the issue
 - [yeoman-blender](https://github.com/gillesfabio/yeoman-blender)
    - [x] Contacted to correct problems
    - [x] Added to Blacklist
    - [ ] Project fixed the issue
 - [yo-node-restify-aws-swagger](https://github.com/pvblicltd/generator-node-restify-aws-swagger)
    - [ ] Contacted to correct problems
    - [x] Added to Blacklist
    - [ ] Project fixed the issue

**Comment by gaboesquivel** [comment]
@eddiemonge, I added those generators to the blacklist in PR #539.  
I think we should just mention the owners here in this thread so they are aware.
Once they solved the problem, they can PR to remove them from blacklist.

**Comment by eddiemonge** [comment]
@hubertburdach can you unpublish or fix https://www.npmjs.com/package/ft-wp please?

**Comment by eddiemonge** [comment]
Closing as I opened a duplicate on the generator list page
