### ISSUE TITLE
Generators not loading

### ISSUE THREAD

**Issue by mcnuttandrew** [yeoman/yeoman.github.io#535]
The generators page is throwing a 503 while trying to load the list of available generators, here are the error messages I got in chrome:

Failed to load resource: the server responded with a status of 503 (Service Unavailable)

XMLHttpRequest cannot load https://yeoman-generator-list.herokuapp.com/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://yeoman.io' is therefore not allowed access. The response had HTTP status code 503.

Problem persists on a Chrome, Firefox, and Safari. I'm guessing it's something to do with heroku, but i'm not sure?

**Comment by SBoudrias** [comment]
Note to the Yeoman team: Let's keep this one open on yeoman.io because we have a lot of reports.

Here's a link to the canonical issue https://github.com/yeoman/yeoman-generator-list/issues/19

**Comment by eddiemonge** [comment]
Closing this as I think its stable using our alternative solutions. we have to decide which solution to keep but we can decide that in the actual issue at the list's repo.
