### ISSUE TITLE
Unclear documentation with regard to composability of sub-generators

### ISSUE THREAD

**Issue by mdotasia** [yeoman/yeoman.github.io#550]
I was reading the composability documentation at http://yeoman.io/authoring/composability.html. It mentions in the **API** section that when setting `settings.local`, you can also use sub-generators. I assume this refers to invoking sub-generators within the same generator. The examples that follow show how to invoke sub-generators form other generators.

Is it possible use composeWith to call a sub-generator from same generator and if yes, what is the syntax? It would be good if you could clarify the composability documentation.

**Comment by SBoudrias** [comment]
Yes and the syntax is the same. The difference is instead of requesting from another generator package, you use a relative paths inside of your project.

Example: https://github.com/yeoman/generator-node/blob/master/generators/app/index.js#L189
