### ISSUE TITLE
Unable to upgrade yo generators

### ISSUE THREAD

**Issue by zhouhao27** [yeoman/yeoman.github.io#570]
I got the following error message when I'm trying to upgrade any of my yo generators:

> UNMET PEER DEPENDENCY yo@>=1.0.0
> npm WARN EPEERINVALID generator-gulp-angular@1.0.0 requires a peer of yo@>=1.0.0 but none was installed.

But the version of yo is 1.5.0. What's wrong with it? Thanks.

**Comment by SBoudrias** [comment]
Peer dependencies should be remove from `generator-gulp-angular`. npm removed support for it.
