### ISSUE TITLE
Generator Search UI results sorting

### ISSUE THREAD

**Issue by vshanbha** [yeoman/yeoman.github.io#578]
As a user I was expecting sorting based on Stars and Installs to be numeric.
When I do the sort it does some sort but the sorting is not numeric. See attached example of sort by installs. May also be possible that this is due to n/w latency.
![screenshot from 2015-12-09 09 49 56](https://cloud.githubusercontent.com/assets/14871482/11676651/83420028-9e5a-11e5-82c8-6803fd1622c6.png)

**Comment by SBoudrias** [comment]
cc @eddiemonge

**Comment by eddiemonge** [comment]
Fixed in https://github.com/yeoman/yeoman.github.io/commit/012ca676bb38a67a8721858f91c4347a9f933243
