### ISSUE TITLE
http://yeoman.io/generators/ can't load generators list

### ISSUE THREAD

**Issue by llamerr** [yeoman/yeoman.github.io#580]
When I open http://yeoman.io/generators/ either in chrome or in firefox, generators list is not loading and `Loading generators...` not going away. In console I have this error

Firefox: 
TypeError: o is undefined
http://yeoman.io/static/bundle-5592.e636d4bf25.js (line 7, col 26155)
Chrome:
list.js:517 Uncaught TypeError: Cannot read property 'childNodes' of undefined

can someone reproduce this issue?

![2015-12-10 10_06_24-generators _ yeoman](https://cloud.githubusercontent.com/assets/1281970/11710166/d6bdd1ac-9f25-11e5-9a4d-22996af7d1f4.png)
![2015-12-10 10_06_41-generators _ yeoman](https://cloud.githubusercontent.com/assets/1281970/11710165/d6bdfbb4-9f25-11e5-8251-edf1e90aa5a0.png)

I have also cleared cache in ff/chrome, but no luck

**Comment by gbiryukov** [comment]
have the same issue

**Comment by ikhemissi** [comment]
It seems that some line (for initializing the generator list) has been removed by accident in the commit https://github.com/yeoman/yeoman.github.io/commit/012ca676bb38a67a8721858f91c4347a9f933243 
Pull-request = https://github.com/yeoman/yeoman.github.io/pull/581

**Comment by eddiemonge** [comment]
Its been fixed but we are working on fixing the deployment problem to get the change up
