### ISSUE TITLE
Dead link in testing.md

### ISSUE THREAD

**Issue by sszuflita** [yeoman/yeoman.github.io#584]
https://github.com/yeoman/yeoman.github.io/blob/source/app/authoring/testing.md#assertions-helpers

^ This section includes a link to http://yeoman.io/generator/assert.html
I believe this link is dead because yeoman assert was moved to a new repo. I think a  link to
https://github.com/yeoman/yeoman-assert/blob/master/README.md
would do the trick.

**Comment by SBoudrias** [comment]
Thanks for the heads up! That's been fixed.
