### ISSUE TITLE
Ship a fresh new codelab for 2016 🍹

### ISSUE THREAD

**Issue by addyosmani** [yeoman/yeoman.github.io#599]
Things our users disliked about the current [codelab](http://yeoman.io/codelab/index.html):

* Too much focus on scaffolding for a framework (Angular). We end up having to explain framework concepts rather than focusing on `yo`. Let's change that.
* Takes too long to get through. Aim to have it be completable in < 15-20 minutes?
* Needs to stay up to date as the generator being used gets updated
* Remind them that `yo` isn't just about Gulp or Grunt. It works fine with npm scripts etc.

Our official generator for Gulp is quite simple and straight-forward, but lacks showing how to use `yo` sub-generators or how it's useful for an app. It's great if you're using React, Polymer or whatever.

Open to any ideas on how to improve the current codelab. :cake: and :cookie: offered for the best suggestion.

**Comment by sindresorhus** [comment]
────────────────────░███░
───────────────────░█░░░█░
──────────────────░█░░░░░█░
─────────────────░█░░░░░█░
──────────░░░───░█░░░░░░█░
─────────░███░──░█░░░░░█░
───────░██░░░██░█░░░░░█░
──────░█░░█░░░░██░░░░░█░
────░██░░█░░░░░░█░░░░█░
───░█░░░█░░░░░░░██░░░█░
──░█░░░░█░░░░░░░░█░░░█░
──░█░░░░░█░░░░░░░░█░░░█░
──░█░░█░░░█░░░░░░░░█░░█░
─░█░░░█░░░░██░░░░░░█░░█░
─░█░░░░█░░░░░██░░░█░░░█░
─░█░█░░░█░░░░░░███░░░░█░
░█░░░█░░░██░░░░░█░░░░░█░
░█░░░░█░░░░█████░░░░░█░
░█░░░░░█░░░░░░░█░░░░░█░
░█░█░░░░██░░░░█░░░░░█░
─░█░█░░░░░████░░░░██░
─░█░░█░░░░░░░█░░██░█░
──░█░░██░░░██░░█░░░█░
───░██░░███░░██░█░░█░
────░██░░░███░░░█░░░█░
──────░███░░░░░░█░░░█░
──────░█░░░░░░░░█░░░█░
──────░█░░░░░░░░░░░░█░
──────░█░░░░░░░░░░░░░█░
──────░█░░░░░░░░░░░░░█░
████──░█░████░░░░░░░░█░
█──█──████──████░░░░░█░
█──█──█──█──█──████████
█──█──████──█──█──────█
█──█──█──█────██──██──█
█──████──█──█──█──────█
█─────█──█──█──█──█████
███████──████──█──────█
──────████──██████████
★══════════★★══════════★

**Comment by sindresorhus** [comment]
> Needs to stay up to date as the generator being used gets updated

That will be a lot easier when the guide is more focused and shorter.

**Comment by SBoudrias** [comment]
As no one really maintains generator-angular anymore, maybe we should offer the spot to a community generator. @zckrs shown some interest into launching users on generator-fountain (angular or react).

**Comment by zckrs** [comment]
...after 78 days in my todo list

We would be honored to update the codelab to get users on our generators FountainJS
We are approaching a beta version involving complex but necessary features in the JavaScript environment
About the content of the tutorial I have total harmony with the remarks made by @addyosmani. 

Here are the steps that I imagine for this codelab:

* Let's Scaffold a Web App with Yeoman: _remove occurrences of Grunt and Bower, replace sentence's AngularJS by React and Angular_
* ~~Meet Yeoman~~: _move from codelab to home|about package_
* Step 1: Set up your dev environment: _prerequisites Nodejs v4, remove bower grunt-cli install_
* Step 2: Install a Yeoman generator: _replace generator-angular by generator-fountain-webapp_
* Step 3: Use a generator to scaffold out your app: _proposé sans imposé une stack React + Webpack + Babel + SASS_
* Step 4: Review the Yeoman-generated app: _quick tour of main folders and files_
* Step 5: Preview your app in the browser: _replace `grunt serve`command by `npm run serve`_
* ~~Step 6: Start writing our AngularJS application~~: _delete from codelab_
* ~~Step 7: Use Bower to install packages~~: _delete from codelab_
* Step 6: Test with Karma and Jasmine: _remove AngularJS code, describe how Karma is congifured, present `npm test` and `npm run test:auto`_
* Step 7: Make Todos persistent with local storage
* Step 8: Get ready for production
* Keep going: _what include in this final step ? link to other generators, to frameworks, etc?_
