### ISSUE TITLE
Issue installing on Win 10

### ISSUE THREAD

**Issue by CurtisLesperance** [yeoman/yeoman.github.io#600]
Hi, I have nodejs and npm installed with the verified version of:
C:\Program Files\nodejs
λ node --version && npm --version
v5.5.0
3.5.3

When I go to install the yeoman etc. I get the following error:
C:\Program Files\nodejs
λ npm install --global yo bower grunt-cli
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
C:\Users\LESPERANCE\AppData\Roaming\npm\bower -> C:\Users\LESPERANCE\AppData\Roaming\npm\node_modules\bower\bin\bower
C:\Users\LESPERANCE\AppData\Roaming\npm\grunt -> C:\Users\LESPERANCE\AppData\Roaming\npm\node_modules\grunt-cli\bin\grunt
C:\Users\LESPERANCE\AppData\Roaming\npm\yo -> C:\Users\LESPERANCE\AppData\Roaming\npm\node_modules\yo\lib\cli.js

> yo@1.6.0 postinstall C:\Users\LESPERANCE\AppData\Roaming\npm\node_modules\yo
> yodoctor

'node' is not recognized as an internal or external command,
operable program or batch file.
C:\Users\LESPERANCE\AppData\Roaming\npm
├── bower@1.7.2
└── grunt-cli@0.1.13

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\LESPERANCE\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "yo" "bower" "grunt-cli"
npm ERR! node v5.5.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE

npm ERR! yo@1.6.0 postinstall: `yodoctor`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yo@1.6.0 postinstall script 'yodoctor'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the yo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     yodoctor
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs yo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls yo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\npm-debug.log

**Comment by SBoudrias** [comment]
Please google issues before opening bug reports http://stackoverflow.com/questions/23412938/node-is-not-recognized-as-an-internal-or-an-external-command-operable-program
