### ISSUE TITLE
Yeoman doesnot generate angular folder

### ISSUE THREAD

**Issue by thiruopti** [yeoman/yeoman.github.io#602]
I install all required dependancy. But yeoman shows error. Doesnot create angular scaffolder.

I use following versions,

Yeoman - 1.6.0
Bower - 1.7.7
Grunt -Cli - V0.1.13
Grunt - V0.4.5

**Comment by SBoudrias** [comment]
What error are you seeing?

Did you try to run `yo doctor`?

**Comment by thiruopti** [comment]
now yeoman creates angular scaffolder  correctly

But whenever i use yo angular shows warning message like karma needed but none was installed.

**Comment by SBoudrias** [comment]
@thiruopti that's NPM letting you know you need to install the peer dependencies yourself.

**Comment by thiruopti** [comment]
k thanks for your reply
