### ISSUE TITLE
Changes to the "Core System" description under Contributing

### ISSUE THREAD

**Issue by JSeed** [yeoman/yeoman.github.io#604]
On the contributing section of the website, there is three "components" listed as the core system:
1. yo, the command line interface to use Yeoman.
2. The runner system which allow to discover and run generators.
3. The base classes you extend to create your own generators. Those classes contain the helper methods to ease the authoring of your own generators.

Both the "runner system" and "base classes" link to the generator github page.

I think that the "runner system" should be changed to the "environment" that generators are run in. 

If everyone agrees and this makes sense I would be happy to submit the changes myself

**Comment by SBoudrias** [comment]
Yeah, please do send a PR.
