### ISSUE TITLE
Code is broken when running as root

### ISSUE THREAD

**Issue by marksteele** [yeoman/yeoman.github.io#613]
I realize you guys have closed tickets related to this before, this is really just to bug you guys into fixing this.

The problem is easy to solve. Fix your code, it's broken. A scaffolding framework should not be trying to change the effective uid or permission masks.

The reason it's broken is that administrators who know what they are doing _can_ fix the problem, but won't want to (as the fix reduces the security of the system).

For example:

```
chmod g+rwx <whatever silly paths are failing>
```

Is not a good idea from a security standpoint.

If you simply do not try to interfere with the user who is running the application (and setting odd permission masks), everything should work just peachy.

```
[root@dev6 web]# yo polymer
/usr/lib/node_modules/yo/node_modules/configstore/index.js:53
                                throw err;
                                ^

Error: EACCES: permission denied, open '/root/.config/configstore/insight-yo.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.create.all.get (/usr/lib/node_modules/yo/node_modules/configstore/index.js:34:26)
    at Object.Configstore (/usr/lib/node_modules/yo/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/lib/node_modules/yo/node_modules/insight/lib/index.js:37:34)
    at Object.<anonymous> (/usr/lib/node_modules/yo/lib/cli.js:163:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
[root@dev6 web]# grep AVC /var/log/audit/audit.log
[root@dev6 web]# chmod g+rwx /root /root/.config /root/.config/configstore
chmod: cannot access '/root/.config/configstore': No such file or directory
```

**Comment by SBoudrias** [comment]
Why are you running as root?

The issue is we have way more people ending up running as root for the wrong reason, and then they wonder why they can't edit files with their code editor, etc etc etc. Root is a big issue, and if you're running on real root related issue, then we're happy because you probably know and understand why it's failing.

**Comment by marksteele** [comment]
Even better question: Why can't I run it as root? (note that I'm not asking why I should/shouldn't).

Why can't the tool manipulate the system as the currently running user instead of trying to impose an artificial constraint?

The sane way most applications deal with dropping privileges is using a configuration setting (eg: runAs:), defaulting as whoever is running the code.

Then if you are trying to do something that requires escalated privileges (eg: switching to a different user) you need root privileges to start the application.

If you default to running as whichever user start the application, you will have no issues regardless of if it's started by a regular user or a privileged one.
