### ISSUE TITLE
Generator search bar filter is not robust enough.

### ISSUE THREAD

**Issue by ojengwa** [yeoman/yeoman.github.io#617]
The generator search bar only filters through the names of generators listed on the page. I think we should have the algorithm filter through the `package.json` tags field as well.

If we can only find generators by the package, some might be had to discover. This is most since correct package NPM names are at a premium.

**Comment by SBoudrias** [comment]
@ojengwa We'd be glad to receive a PR improving the situation!

**Comment by mischah** [comment]
Sounds like a good idea. We could add filters based on npm keywords for the generators.

This needs changes in [yeoman/yeoman-generator-list](https://github.com/yeoman/yeoman-generator-list) as well to provide keywords in the JSON file that the generator list in this repo is consuming.

**Comment by mischah** [comment]
Obsolete with the merge of #763
