### ISSUE TITLE
Getting trouble with on your tutorial

### ISSUE THREAD

**Issue by Jantastic** [yeoman/yeoman.github.io#623]
your tutorial has an issue (http://yeoman.io/codelab/install-generators.html)

by installing:
`npm install --global generator-angular@0.11.1 generator-karma`
you will run into an error:
`npm WARN generator-angular@0.11.1 requires a peer of yo@>=1.0.0 but none was installed.`

these guys says:
npm3 no longer auto installers peer deps so you have to install them manually.
https://github.com/yeoman/generator-angular/issues/1192

so maybe you would update the tutorial?

cheers Jan

**Comment by eddiemonge** [comment]
You missed step one where it says to install yo globally http://yeoman.io/codelab/setup.html
