### ISSUE TITLE
Side bar nav overlapping footer on scrolling to bottom

### ISSUE THREAD

**Issue by vikas-parashar** [yeoman/yeoman.github.io#630]
Right side nav on [codelab tutorial page](http://yeoman.io/codelab/index.html) overlaps the footer when we scroll to the bottom.

![untitled gif](https://cloud.githubusercontent.com/assets/5694967/14583201/2537fc78-0438-11e6-912b-4fbd9d55babe.gif)

**Comment by oguzzkilic** [comment]
@SBoudrias

**Comment by kevva** [comment]
Fixed in https://github.com/yeoman/yeoman.github.io/commit/490a6dfabaf40aac099bc26c87abefa6882aec2a.
