### ISSUE TITLE
Generator list broken

### ISSUE THREAD

**Issue by jeffhuys** [yeoman/yeoman.github.io#637]
The generator list keeps displaying "Loading generators...". The console gives me `TypeError: undefined is not an object (evaluating 'a.offset().top')`, don't know if it's related.

**Comment by pysco68** [comment]
Same around here

**Comment by SBoudrias** [comment]
Caused by #635 - I don't have time to fix it right now, but if anyone is nice enough to send a PR fix.

cc @oguzzkilic

**Comment by oguzzkilic** [comment]
@SBoudrias  I'm interested in problems.
