### ISSUE TITLE
grunt serve => "Aborted due to warnings" error

### ISSUE THREAD

**Issue by oguzzkilic** [yeoman/yeoman.github.io#639]
Hi everyone.

"grunt serve" There is a problem with. Error message: "Aborted due to warnings"

Do you have any idea?

.tmp/normalize.css sometimes the message can sometimes be .tmp/prettify.css.

![error](https://cloud.githubusercontent.com/assets/3652404/14799212/0eb203f0-0b44-11e6-9047-f08b47469a50.jpg)

**Comment by eddiemonge** [comment]
This should be opened on the generator that created the project.
