### ISSUE TITLE
Generator list not updating

### ISSUE THREAD

**Issue by tushar-chauhan** [yeoman/yeoman.github.io#642]
Hi,

I have created and published a [yeoman generator](https://www.npmjs.com/package/generator-angular2-sass-gulp-heroku) few hours ago. Even after much time, I am unable to find it on the generators page. This led me to checkout many discussions regarding blacklisted generators and I came across this URL: https://yeoman-generator-list.herokuapp.com.

I can see my generator in the JSON response from it, but I don't know whether it is blacklisted. Also, that JSON response has updated info regarding many existing generators which is not being updated on the generators search page.

Does the generators list really gets updated in an hour? Because that JSON response shows more than 4000 generators and the website is currently(at the time of writing this) listing only 3751 generators.

Any help in right direction will be great.

**Comment by SBoudrias** [comment]
cc @eddiemonge

**Comment by eddiemonge** [comment]
Checking it now  but may take time to troubleshoot since I'm at ngconf

**Comment by eddiemonge** [comment]
> https://yeoman-generator-list.herokuapp.com

This isn't used and we are going to take it down soon. Thought we already did actually

**Comment by eddiemonge** [comment]
Looked like new relic crashed it somehow. I'll put in some time next week to make this more crash resilient and crash restartable

**Comment by eddiemonge** [comment]
So it's updated. Closing this but going to track it in its repo

**Comment by tushar-chauhan** [comment]
@eddiemonge On which repo this is being tracked? I guess this issue is happening again.
