### ISSUE TITLE
TypeError: e.sort is not a function on generators page

### ISSUE THREAD

**Issue by javor** [yeoman/yeoman.github.io#645]
Going on page http://yeoman.io/generators/ thrown in firefox/chrome console: 'TypeError: e.sort is not a function.'

No results given.

**Comment by oguzzkilic** [comment]
@javor not see any problem..

**Comment by eddiemonge** [comment]
I also don't get this.

**Comment by wesleytodd** [comment]
I am getting this, came to file the same issue and found this here.  I am on Chrome/OSx fully up to date.

Digging in a bit I see this is the only reference to a method `sort` on `e`:

```javascript
t.getJSON('https://storage.googleapis.com/generators.yeoman.io/cache.json').done(function(e){s.html(r({modules:e.sort(function(e,t){return e.stars===t.stars?0:e.stars<t.stars?1:-1})}));
```

Hope that helps :)

**Comment by SBoudrias** [comment]
So this would happens when we don't receive what we expect from the server.

**Comment by hemanth** [comment]
We need a check [here](https://github.com/yeoman/yeoman.github.io/blob/77f78e9dd243969bec96199dab8a16a85460bd0c/app/assets/js/generator.js#L23) for plugin existence.

**Comment by 4tron** [comment]
I am still getting this issue

**Comment by hoshsadiq** [comment]
I'm getting this issue too albeit slightly different. I have tried it with all chrome extensions disabled to no avail.

Just in case it might prove useful, here's the stacktrace. I can't unminify it using Chrome's devtools as for some reason the file generator.js shows up as empty:
```
Uncaught TypeError: a.sort is not a function
(anonymous function) @ generator.js:25
j @ jquery.min.js:2
fireWith @ jquery.min.js:2
x @ jquery.min.js:4
(anonymous function) @ jquery.min.js:4
```

Getting this with both Firefox and Chrome

**Comment by szechyjs** [comment]
I get the same problem.

```
Uncaught TypeError: a.sort is not a function
    at Object.<anonymous> (http://yeoman.io/static/bundle-5266.530c0a01e3.js:1:20799)
```

Which points to:
```js
b.getJSON('https://storage.googleapis.com/generators.yeoman.io/cache.json')
  .done(function(a) {
    e.html(d({
      modules: a.sort(function(a,b) {
        return a.stars === b.stars ? 0 : a.stars < b.stars ? 1 : -1
      })
    })
);
```

Since the code is uglified I'm not sure what `d` is, but from visiting the `cache.json` url, the object is empty. Could the problem be that it is trying to sort an empty object?

**Comment by SBoudrias** [comment]
An empty array is still sortable. Looks like we're sometime receiving undefined or null from the server. We should add a guard against that state.

**Comment by hemanth** [comment]
Should we change the endpoint to `now.sh` or similar? @SBoudrias

**Comment by jarodccrowe** [comment]
Getting this error now also.

**Comment by drm-code** [comment]
@SBoudrias I'm still getting same error, 2 hours ago I was getting the list of generators fine, what happened???

**Comment by SBoudrias** [comment]
The batch update might've failed and push broken data.

**Comment by eddiemonge** [comment]
Are people still seeing this?

**Comment by SBoudrias** [comment]
@eddiemonge it seems to be intermitent. Could it be a race condition?

**Comment by eddiemonge** [comment]
Hopefully [this fixes](https://github.com/yeoman/yeoman.github.io/commit/775e8e22c1412dbd10e65cf774f44befadb0c947) it

**Comment by AlejandroGonzalezZ** [comment]
and how they fixed it finally ?, I'm stuck right here!
