### ISSUE TITLE
installing generation according to yeoman step2

### ISSUE THREAD

**Issue by lilachreshef** [yeoman/yeoman.github.io#648]
Hey there

**Running this command:**
npm install --global generator-angular@0.11.1 generator-karma

**causing:**
npm WARN generator-angular@0.11.1 requires a peer of yo@>=1.0.0 but none was installed.

Thanks
Lilach

**Comment by SBoudrias** [comment]
That's only a warning.

Did you install `yo` yet?

**Comment by lilachreshef** [comment]
yes, I made step by step starting at http://yeoman.io/codelab/setup.html...
but i didnt install git first... so I made all again and now everything is almost work
when I run the grunt serve the browser show:
the application without the css..... in the app/index.html there are linkes to 
node_modules directory   and not to ../node_modules
