### ISSUE TITLE
Windows Issue

### ISSUE THREAD

**Issue by David-Carty** [yeoman/yeoman.github.io#649]
Press <space> to select menu options does not work in windows 10.  Tested via cmd.exe and gitbash.  All latest files included.

**Comment by kevva** [comment]
I'm not sure I understand what you're asking here. But it might be related to https://github.com/yeoman/yo/issues/360.

**Comment by David-Carty** [comment]
Yes sir that is correct it does relate to that issue.  I have resolved my own personal issue by running the generator, the best I could, and then editing the files manually.  Not ideal, but it's solved my problem.  Clearly there is some issue with the keyboard and cmd prompt in the context of Yeoman.  The generator that I was using was: 'generator-webapp'.  Hope this helps.
