### ISSUE TITLE
newer versions needed in yo generate

### ISSUE THREAD

**Issue by Vonnie** [yeoman/yeoman.github.io#651]
The doc instructs to send this msg for newer versions than what doc has.
These are:
1.8.3: yo
1.7.9: bower
grunt-cli v1.2.0: grunt

**Comment by SBoudrias** [comment]
Can you clarify what you mean?

**Comment by Vonnie** [comment]
I'm following along on yeoman codelab.

At the bottom of the page at http://yeoman.io/codelab/setup.html, it says if 'running into issues' with new versions, open an issue with the link. I do have issues, but at the time I read it wrong, as to notify on newer versions.

I have come across two problems. I've solved one, which you may need to know. The generated version for bootstrap is incorrect. It had like 3.3.2. My website was not bootstrapized. Had to change bower.js & manually install for version 3.3.4. Current bootstrap version 3.3.6 does not work, as 3.3.2.

My second problem is the sort. I've gone over the docs, Gone over npmjs angular-ui-sortable docs, too. My items do not sort.

My unsorted list:
![yeomanissue001-a](https://cloud.githubusercontent.com/assets/1789196/15709831/751a72fe-27cc-11e6-8ee6-2801c8d09288.jpg)

bower.js defined dependencies:
![yeomanissue001-b](https://cloud.githubusercontent.com/assets/1789196/15709843/88641414-27cc-11e6-8c8f-bb2da8c133b6.jpg)

main.html
![yeomanissue001-c](https://cloud.githubusercontent.com/assets/1789196/15709849/8e2a21ea-27cc-11e6-825c-d31ae35797eb.jpg)

**Comment by Vonnie** [comment]
Found the angular-ui-sortable versions are different.

My generated bower.js has 0.14.0. Doc has 0.13.3. Request to install 0.13.3 had a not found angular-ui-sortable#0.13.3.

**Comment by eddiemonge** [comment]
The format was updated recently. Want to try it and report on it
