### ISSUE TITLE
Clean view for new users (reduce confusion when adapting)

### ISSUE THREAD

**Issue by npbenjohnson** [yeoman/yeoman.github.io#655]
There is so much deprecated functionality right now. Combined with the other navigation/display issues in here it creates a fairly high barrier to entry using the documentation. Since it can hopefully be implemented with just a jsdoc generation switch, it would be great to have an additional version of the docs which doesn't include deprecated functionality. (Or if work is being done on the template anyway, being able to hide deprecated functionality would work too)

**Comment by eddiemonge** [comment]
Need a way to access the different versions of the docs here (or in the generator repo)

**Comment by mischah** [comment]
Duplicates yeoman/yeoman#1485.
