### ISSUE TITLE
codelab Step 7: data not being being persisted to local storage

### ISSUE THREAD

**Issue by gViro** [yeoman/yeoman.github.io#665]
I've gone through the [codelab](http://yeoman.io/codelab/local-storage.html) twice now, and the data is not being persisted to local storage. 

I've had a look at [redux-localstorage](https://github.com/elgerlambert/redux-localstorage/tree/1.0-breaking-changes) README and I've noticed a few things:

- the npm installation command given in the README is different than the one in the codelab.

- the code shown in the README differs from that shown in the codelab, as well as from whatever npm/Yeoman is pulling in/scaffolding. (please see image below) 

Finally, this step starts out by implying that there was a previously encountered issue, namely, "items not persisting when the browser refreshes with our React/Redux mytodo app". However, this issue does not get mentioned in any of the previous steps. 
My initial reaction was that I had missed a step or skipped some content. 
Confusing. 

![screen shot 2016-07-21 at 16 50 06](https://cloud.githubusercontent.com/assets/2657301/17029607/c0ead1c4-4f63-11e6-8bb9-297fc779193b.png)

**Comment by zckrs** [comment]
Hi @gViro 

> the npm installation command given in the README is different than the one in the codelab.

If you look [readme in master branch](https://github.com/elgerlambert/redux-localstorage#redux-localstorage) the maintainer drop a note `NOTE: Be sure to check out the 1.0-breaking-changes branch (available on npm as redux-localstorage@rc).`


> the code shown in the README differs from that shown in the codelab, as well as from whatever npm/Yeoman is pulling in/scaffolding.

The code shown in the codelab is present to replace entirely your configureStore.js 


> Finally, this step starts out by implying that there was a previously encountered issue, namely [...]

The Step 7 is named "MAKE TODOS PERSISTENT WITH LOCAL STORAGE"  but this step can be totally skipped. This is just a example of hacking TodoApp. Maybe I should add a note about that.




Finally sorry if I misunderstood your issue :anguished:.

**Comment by gViro** [comment]
Thanks for your helpful reply.
