### ISSUE TITLE
Blacklist link doesn't work

### ISSUE THREAD

**Issue by tiagoporto** [yeoman/yeoman.github.io#679]
Hi, I have a generator [Swill Boilerplate](https://www.npmjs.com/package/generator-swill-boilerplate) and the information in the site is out of date. The link to blacklist http://yeoman.io/generators/#linkneeded doesn't work and I don't know if it is there.

What can I do to update the info?

**Comment by tiagoporto** [comment]
Hello, someone can help?

**Comment by SBoudrias** [comment]
// @eddiemonge Do you know where we store the blacklist now?

**Comment by SBoudrias** [comment]
Actually, we have a blacklist here: https://github.com/yeoman/yeoman-generator-list/blob/master/src/blacklist.js

But I'm not 100% sure it's the one we use.

**Comment by tiagoporto** [comment]
Thanks @SBoudrias, my generator isn't on this list. But the info in the yeoman site it's outdated. Do you know how can I update this?

**Comment by zckrs** [comment]
I just run local version of https://github.com/yeoman/yeoman-generator-list

Voilà result of yeoman generator list

https://gist.github.com/zckrs/4e36d0e8a6be99b681299f23bafb5cfc

[blacklist.json](https://github.com/yeoman/yeoman-generator-list/blob/master/src/blacklist.js) are correctly used.

@tiagoporto your generator are present in my local list

```
    {
        "description": "🍺 The front-end Boilerplate that you need to start multi-device development, easy to customize",
        "downloads": 16082,
        "name": "swill-boilerplate",
        "official": false,
        "owner": {
            "name": "Tiago Porto",
            "site": "http://tiagoporto.com"
        },
        "site": "http://swillboilerplate.rocks/",
        "stars": 25,
        "timeSince": "9 days ago",
        "updated": "2016-10-04T00:52:38.137Z"
    }
```

IMO we have some problem with the hosted solution for yeoman-generator-list.

But I miss information on the solution chosen

**Comment by tiagoporto** [comment]
@zckrs This local information is correct. But in the website it's outdated.

The blacklist link still not working.

**Comment by SBoudrias** [comment]
Information on website will be updated eventually. There's delay.

**Comment by tiagoporto** [comment]
@SBoudrias the information still outdated.

**Comment by SBoudrias** [comment]
We're hitting rate limiting issues for the list data fetching because we have too many generators now. This is being addressed and will eventually be fixed.

**Comment by eddiemonge** [comment]
Info should be updated now. Only a temporary fix though
