### ISSUE TITLE
The stars count on the generators list doesn’t match Github stars

### ISSUE THREAD

**Issue by mischah** [yeoman/yeoman.github.io#681]
Hej,

seems like they are out of sync. At least for a few generators.

## Example 1
![fake-backend](https://cloud.githubusercontent.com/assets/441011/19268311/134c7cfc-8fb4-11e6-8104-0056359e16fc.png)

https://github.com/micromata/generator-http-fake-backend has currently **21** stars.

## Example 2
![chrome-extension](https://cloud.githubusercontent.com/assets/441011/19268501/239b5dfc-8fb5-11e6-922d-b8bc313a0c11.png)

https://github.com/yeoman/generator-chrome-extension has currently **1414** stars.

**Comment by mischah** [comment]
I might find some time to have a look into that within the next couple of days.

**Comment by sindresorhus** [comment]
// @eddiemonge

**Comment by zckrs** [comment]
FYI I run local version of https://github.com/yeoman/yeoman-generator-list

Voilà result of yeoman generator list

https://gist.github.com/zckrs/4e36d0e8a6be99b681299f23bafb5cfc

**Comment by mischah** [comment]
Thank you very much.

The numbers of stars are now correct for: https://github.com/yeoman/generator-chrome-extension 

Same here https://storage.googleapis.com/generators.yeoman.io/cache.json

But this one from me still has zero stars according to that JSON:
https://github.com/micromata/generator-http-fake-backend 

Locally generated as well as online.

Is something wrong with the metadata from my generator?

This is a snippet out of that huge JSON:
```
{
        "description": "Build a fake backend by providing the content of JSON files or JavaScript objects through configurable routes",
        "downloads": 242,
        "name": "http-fake-backend",
        "official": false,
        "owner": {
            "name": "Michael Kühnel",
            "site": "http://micromata.de"
        },
        "site": "https://github.com/micromata/generator-http-fake-backend",
        "stars": 0,
        "timeSince": "6 days ago",
        "updated": "2016-10-06T23:43:11.179Z"
    }
```

And here’s the link to npm: https://www.npmjs.com/package/generator-http-fake-backend

**Comment by eddiemonge** [comment]
Problem is we need to change polling now that we are over 5000 generators. Github's rate limiting is starting to affect us and need to switch to doing things in batches

**Comment by eddiemonge** [comment]
Closing this as it should be opened on the list repo and I'm already aware of it for there. I'll try to get to it in the next couple of days

**Comment by mischah** [comment]
👌 Thanks for the info.

**Comment by diegohaz** [comment]
It seems to work here: https://github.com/yeoman/yeoman-generator-list/issues/50
