### ISSUE TITLE
Storage docs is missing information about .yo-rc-global.json

### ISSUE THREAD

**Issue by mischah** [yeoman/yeoman.github.io#684]
Hej, I’m confused.

I have a file named `.yo-rc-global.json` in my home directory.
Guess thats what stored prompts (via `store: true`) are living?!?

But why is neither `store: true` nor `.yo-rc-global.json` mentioned in http://yeoman.io/authoring/storage.html? 
Because it is a whole different story?

Cheers, Michael

**Comment by SBoudrias** [comment]
The main reason is that it is used as a cache for prompts, but it's not directly usable by the generator consumers. So there's no reason from the system point of view to talk about it.

**Comment by mischah** [comment]
Okay.

**Comment by marekj** [comment]
I actually rely on `~/yo-rc-global.json` to store credentials which I don't want to store in a local `yo-rc`. That way I can use the generator to create a new app in a new dir and I can reuse the earlier info.  Is this scenario if usage common? if so adding docs would be useful.

I've found yo-rc-global storage by accident (and by looking at prompt() source code.
