### ISSUE TITLE
No generators showing up

### ISSUE THREAD

**Issue by scottaj91** [yeoman/yeoman.github.io#707]
Generator search is currently broken. Not finding any generators to search through.

Could this be related?
http://blog.npmjs.org/post/154912817335/better-search-is-here

See below for page preview:

![image](https://cloud.githubusercontent.com/assets/4737932/21987387/372fcd20-dbfb-11e6-93ef-f9d86f3504fa.png)

**Comment by zckrs** [comment]
https://npms.io/ is down.

So our last build push a empty list :(

https://github.com/yeoman/yeoman-generator-list/blob/cache-generators-list/cache.json

**Comment by scottaj91** [comment]
Ah yes. And back up now. All working again! 👍
