### ISSUE TITLE
My package generator-mage2 not found on yeoman.io/generators

### ISSUE THREAD

**Issue by ousmanedev** [yeoman/yeoman.github.io#713]
Hours ago, I published my package [generator-mage2](https://npmjs.com/package/generator-mage2) on the npm repository following the criterias to get visible on yeoman.io/generators page.
Unfortunately a search for mage2 on that page, gives a _not found_ message.
To make sure, I've followed the guidelines, I run [yeoman-generator-list](https://github.com/yeoman/yeoman-generator-list) and it was able to retrieve my generator.

**Comment by SBoudrias** [comment]
Looks like we're currently updating once every 24 hours - see https://github.com/yeoman/yeoman-generator-list/tree/cache-generators-list

@zckrs is the hourly task down or did we get rid of it?

**Comment by zckrs** [comment]
IMO the task is down. I will check that.

**Comment by zckrs** [comment]
@SBoudrias permissions change ???

When I post on ` https://api.travis-ci.org/repo/yeoman\%2Fyeoman-generator-list/requests` I get this error :-/
```
{
  "@type": "error",
  "error_type": "insufficient_access",
  "error_message": "operation requires create_request access to repository",
  "resource_type": "repository",
  "permission": "create_request",
  "repository": {
    "@type": "repository",
    "@href": "/repo/1076330",
    "@representation": "minimal",
    "id": 1076330,
    "name": "yeoman-generator-list",
    "slug": "yeoman/yeoman-generator-list"
  }
}     
```

**Comment by zckrs** [comment]
Solved!

**Comment by ousmanedev** [comment]
Thanks !
