### ISSUE TITLE
broken link for runContext

### ISSUE THREAD

**Issue by harryi3t** [yeoman/yeoman.github.io#720]
The link for `runContext` is broken on http://yeoman.io/authoring/testing.html
![image](https://cloud.githubusercontent.com/assets/5207331/24860062/736aaf60-1e10-11e7-8eb6-4571f8517244.png)
![image](https://cloud.githubusercontent.com/assets/5207331/24860068/7bda5fec-1e10-11e7-920c-1fe9712b9dab.png)

**Comment by SBoudrias** [comment]
Thanks for the report, pushed an update to fix the link.
