### ISSUE TITLE
Problem fetching the generator list

### ISSUE THREAD

**Issue by braincap** [yeoman/yeoman.github.io#721]
http://yeoman.io/generators/ keeps giving "There was a problem fetching the generator list. Please try again later." error.

![issue](https://cloud.githubusercontent.com/assets/11663988/25034614/c6d515f8-20b5-11e7-859f-9584a049a72a.jpg)

**Comment by beatrix-bodo** [comment]
It's showing this page for me. When I'm trying to search, nothing happens, it doesn't even reload the page.  

![image](https://user-images.githubusercontent.com/10792235/27222477-af348c7c-528c-11e7-976c-94487a3deaf7.png)

**Comment by zckrs** [comment]
We use https://npms.io/ to get several info about generator (like stars)

Currently they have some issue
https://twitter.com/npms_io/status/875658798056210432


To fix that I push the last state of generator list. Clear your cookie or wait 30 minutes
