### ISSUE TITLE
Automatic Generic Yeoman Generator

### ISSUE THREAD

**Issue by Ayobamideleope** [yeoman/yeoman.github.io#740]
Hello, I was thinking can't we add a feature to yeoman website whereby instead of searching through a lot of generators just by name (which can be sometimes misleading and strenuous), the search would be made based on selections of what a developer is looking to include in the generator. So, the list can be greatly reduced and concise.

**Comment by mischah** [comment]
We could add filters based on npm keywords for the generators.
I’m not sure how good that would work out. Or do you have any other idea for a data source?

**Comment by mischah** [comment]
Just saw that this in duplicates #617
