### ISSUE TITLE
Set up deploying to netlify to preview PRs 

### ISSUE THREAD

**Issue by mischah** [yeoman/yeoman.github.io#744]
Hej,

it would be awesome to setup netlify automatically deploy PRs to preview changes in the browser.

See this [feature](https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/) and this [example](https://github.com/micromata/baumeister.io/pull/4#issuecomment-336448418).

I tried to set it up, but it seems that I’m missing Privileges:
![image](https://user-images.githubusercontent.com/441011/32079958-538d701c-baad-11e7-99c1-a60c56b86a74.png)

Could you grant me access to set this up?

**Comment by SBoudrias** [comment]
@mischah done, you're now the Yeoman site team maintainer (you can add contributors to this repo).

**Comment by mischah** [comment]
@SBoudrias Thanks, seems that this isn’t enough.
I still don’t see any Yeoman repo on netlify. Guess one has to be an admin of a repo to set up netlify for it.

**Comment by mischah** [comment]
Thank @SBoudrias, I now see the repo at netlify and going to set it up 👍

**Comment by mischah** [comment]
It works: https://farmer-lot-44525.netlify.com/ 🎉 

… and should deploy pull requests as well.

**Comment by mischah** [comment]
It works: https://yeoman.netlify.com/ 🎉 

… and should deploy pull requests as well.

**Comment by SBoudrias** [comment]
Seems great! BTW there's a mixed content warning (ga script)

**Comment by mischah** [comment]
Thanks for catching that. Going to resolve that later.
