### ISSUE TITLE
Generators list fails due to lack of https

### ISSUE THREAD

**Issue by drewswaycool** [yeoman/yeoman.github.io#748]
https://github.com/yeoman/yeoman.github.io/blob/da63aa07384b4030ac351774cd57c2d4fdd06cd5/app/assets/js/generator.js#L28

`Request URL:https://cdn.rawgit.com/yeoman/yeoman-generator-list/d15a5c3044512a9142a16f1fd2ad213e3380b08b/cache.json`

`Referrer Policy:no-referrer-when-downgrade`

`http` works fine.. might be a cert issue on their part.

**Comment by mischah** [comment]
Works over here right now.

@drewswaycool are you still having issues?

**Comment by mischah** [comment]
Closing because of lack of feedback.
