### ISSUE TITLE
Deployment doesn’t work

### ISSUE THREAD

**Issue by mischah** [yeoman/yeoman.github.io#753]
It’s because Travis can’t execute `npm run-script deploy`.

This is pointing to `"grunt deploy-travis` which needs a GitHub token:
![image](https://user-images.githubusercontent.com/441011/35089844-5e059ebc-fc38-11e7-8815-a98d733419be.png)

Surprisingly there is no token in the travis build settings:
![image](https://user-images.githubusercontent.com/441011/35089921-87c442f8-fc38-11e7-831f-1cbc99431342.png)

@SBoudrias Could you paste your Github Token to Travis?

**Comment by SBoudrias** [comment]
@mischah do we still need travis?

**Comment by SBoudrias** [comment]
The token should be encrypted here: https://github.com/yeoman/yeoman.github.io/blob/source/.travis.yml#L28

**Comment by mischah** [comment]
> do we still need travis?
Sadly yes.
The DNS entries still point to Github pages.

Going to ping Addy again.

> The token should be encrypted here: https://github.com/yeoman/yeoman.github.io/blob/source/.travis.yml#L28

Ah. Didn’t see this.

**Comment by mischah** [comment]
Fixed with merging #764
