### ISSUE TITLE
Add me to yeoman GitHub Org

### ISSUE THREAD

**Issue by YoginthS** [yeoman/yeoman.github.io#758]
Add me to yeoman GitHub Org, Know about me https://yoginth.ml

**Comment by mischah** [comment]
Huh? Why should we? You haven’t [contributed](https://github.com/search?utf8=✓&q=+is%3Apr+author%3AYoginthS+archived%3Afalse++org%3Ayeoman&type=) yet.

**Comment by mischah** [comment]
Sorry, I guess my answer wasn’t that welcoming. First starting point for you is http://yeoman.io/contributing/

Feel free to visit our Gitter Chatrooms if you have any question.

**Comment by YoginthS** [comment]
No problem
